# Generated by Django 3.2.5 on 2021-07-07 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('genre', models.CharField(choices=[('Narrative', 'Narrative'), ('Fiction', 'Ficton'), ('Non-Fiction', 'Non-Fiction'), ('Mystery', 'Mystery'), ('Science-Fiction', 'Science-Fiction'), ('Historical-Fiction', 'Historical-Fiction'), ('Fantasy', 'Fantasy'), ('Romance', 'Romance'), ('Horror', 'Horror'), ('Thriller', 'Thriller')], max_length=200)),
                ('language', models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Marathi', 'Marathi'), ('Sanskrit', 'Sanskrit')], max_length=200)),
            ],
        ),
    ]
