# Generated by Django 3.2.5 on 2021-07-07 06:31

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Narrative', 'Narrative'), ('Fiction', 'Ficton'), ('Non-Fiction', 'Non-Fiction'), ('Mystery', 'Mystery'), ('Science-Fiction', 'Science-Fiction'), ('Historical-Fiction', 'Historical-Fiction'), ('Fantasy', 'Fantasy'), ('Romance', 'Romance'), ('Horror', 'Horror'), ('Thriller', 'Thriller')], max_length=100),
        ),
    ]
